C:\Github Repos\automate-personal-financeError running './cleaning/refresh_excel.py': Command '['C:/Github Repos/automate-personal-finance/.venv/Scripts/python.exe', './cleaning/refresh_excel.py']' returned non-zero exit status 1.C:\Github Repos\automate-personal-financeError running './cleaning/refresh_excel.py': Command '['C:/Github Repos/automate-personal-finance/.venv/Scripts/python.exe', './cleaning/refresh_excel.py']' returned non-zero exit status 1.C:\Github Repos\automate-personal-financeError running './scraping/scraping.py': Command '['C:/Github Repos/automate-personal-finance/.venv/Scripts/python.exe', './scraping/scraping.py']' returned non-zero exit status 1.Error running './cleaning/refresh_excel.py': Command '['C:/Github Repos/automate-personal-finance/.venv/Scripts/python.exe', './cleaning/refresh_excel.py']' returned non-zero exit status 1.C:\Github Repos\automate-personal-financeError running './cleaning/refresh_excel.py': Command '['C:/Github Repos/automate-personal-finance/.venv/Scripts/python.exe', './cleaning/refresh_excel.py']' returned non-zero exit status 1.