[2023-07-26T21:51:11.103+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: empower_to_ggdrive.scraping manual__2023-07-26T21:51:08.721694+00:00 [queued]>
[2023-07-26T21:51:11.112+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: empower_to_ggdrive.scraping manual__2023-07-26T21:51:08.721694+00:00 [queued]>
[2023-07-26T21:51:11.113+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-26T21:51:11.131+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): scraping> on 2023-07-26 21:51:08.721694+00:00
[2023-07-26T21:51:11.137+0000] {standard_task_runner.py:57} INFO - Started process 305 to run task
[2023-07-26T21:51:11.141+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'empower_to_ggdrive', 'scraping', 'manual__2023-07-26T21:51:08.721694+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/empower_to_ggdrive.py', '--cfg-path', '/tmp/tmpzfftl6h1']
[2023-07-26T21:51:11.145+0000] {standard_task_runner.py:85} INFO - Job 138: Subtask scraping
[2023-07-26T21:51:11.272+0000] {task_command.py:410} INFO - Running <TaskInstance: empower_to_ggdrive.scraping manual__2023-07-26T21:51:08.721694+00:00 [running]> on host 56479707abb6
[2023-07-26T21:51:11.388+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='empower_to_ggdrive' AIRFLOW_CTX_TASK_ID='scraping' AIRFLOW_CTX_EXECUTION_DATE='2023-07-26T21:51:08.721694+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-26T21:51:08.721694+00:00'
[2023-07-26T21:51:11.393+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tasks.py", line 5, in scraping
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2023-07-26T21:51:11.406+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=empower_to_ggdrive, task_id=scraping, execution_date=20230726T215108, start_date=20230726T215111, end_date=20230726T215111
[2023-07-26T21:51:11.421+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 138 for task scraping (No module named 'selenium'; 305)
[2023-07-26T21:51:11.433+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-26T21:51:11.466+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
